apiVersion: v1
kind: Pod
metadata:
  name: webapp-pod
  labels:
    app: webapp
    type: frontend
  namespace: dev
spec:
  containers:
  - name: nginx-controller
    image: nginx
    resources:
      requests:
        memory: "4Gi" # Mi, Gi, Ki 1024 bytes || G, M, K 1000 bytes
        cpu: 2 # 1 cpu === 1 AWS,GCP,Azure,Hyperthread vCPU
      limits: 
        memory: "2Gi"
        cpu: 2
  - name: busybox
    image: busybox
    resources:
      requests:
        memory: "3Gi" # Mi, Gi, Ki 1024 bytes || G, M, K 1000 bytes
        cpu: 2 # 1 cpu === 1 AWS,GCP,Azure,Hyperthread vCPU
      limits: 
        memory: "1Gi"
        cpu: 2