apiVersion: v1
kind: Pod
metadata:
  name: webapp-pod
  labels:
    app: webapp
    type: frontend
  namespace: dev
spec:
  containers:
  - name: nginx-controller
    image: nginx
  - name: busybox
    image: busybox