apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp-deployment
  labels:
    app: webapp
    type: frontend
spec:
   replicas: 3
   strategy:
     type: RollingUpdate
     rollingUpdate:
        maxSurge: 25%
        maxUnavailable: 25%
   selector:
     matchLabels:
       type: frontend
   template:
  #  Pod file section
     metadata:
       name: webapp-pod
       labels:
         app: webapp
         type: frontend
     spec:
      containers:
      - name: nginx-controller
        image: nginx
      - name: busybox
        image: busybox
  #  Pod file section
