apiVersion: v1
kind: Pod
metadata:
  name: webapp-pod
  labels:
    app: webapp
    type: frontend
  namespace: dev
spec:
  nodeName: node01 # Scheduling only for creation time
  nodeSelector: # Scheduling select node by label
    size: Large # Scheduling node labels
  tolerations: # Scheduling toleration
    - key: "app"
      operator: "Equal"
      value: "blue"
      effect: "NoSchedule"
  containers:
  - name: nginx-controller
    image: nginx
    command: 
    - sleep
    - "1000"
  - name: busybox
    image: busybox
    env:
      - name: ENVIRONMENT
        value: dev
    ports:
      - containerPort: 8080