apiVersion: v1
kind: ConfigMap
data:
  my-scheduler-config.yaml: |
    apiVersion: kubescheduler.config.k8s.io/v1beta2
    kind: KubeSchedulerConfiguration
    profiles:
      - schedulerName: my-scheduler
    leaderElection:
      leaderElect: false
metadata:
  name: my-scheduler-config
  namespace: kube-system