apiVersion: v1
kind: Pod
metadata:
  name: webapp-pod
  labels:
    app: webapp
    type: frontend
  namespace: dev
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution: # preferredDuringSchedulingIgnoredDuringExecution
        nodeSelectorTerms:
          - matchExpressions:
              - key: size
                operator: In # In, NotIn, Exists, DoesNotExist, Gt, Lt
                values:
                  - Large
                  - Medium
  containers:
  - name: nginx-controller
    image: nginx
  - name: busybox
    image: busybox