apiVersion: v1
kind: PersistentVolume
metadata: 
  name: pv-vol1
spec:
  accessModes:
    - ReadWriteOnce # ReadOnlyMany | ReadWriteOnce | ReadWriteMany
  capacity:
    storage: 1Gi
  hostPath:
    path: /tmp/data
    # OR
  awsElasticBlockStore:
    volumeID: <vol-id>
    fsType: ext4
  persistentVolumeReclaimPolicy: Retain # Retain | Delete | Recycle (Keep data only) - When the associated PVC deleted this will manage what will happen to the persistent volume 
