apiVersion: v1
kind: Pod
metadata:
  name: mypod
spec:
  containers:
    - name: alpine
      image: alpine
      volumeMounts:
        - mountPath: "/var/www/html"
          name: mypd
  volumes:
    - name: mypd
      persistentVolumeClaim:
        claimName: myclaim
