apiVersion: v1
kind: Pod
metadata:
  name: webapp-pod
  labels:
    app: webapp
    type: frontend
  namespace: dev
spec:
  containers:
  - name: nginx-controller
    image: nginx
    envFrom:
      - secretRef:
          name: app-config
  - name: busybox-controller
    image: busybox
    env:
      - name: APP_COLOR
        valueFrom:
            secretKeyRef:
               name: app-config
               key: APP_COLOR
  volumes:
    - name: app-secret-volume
      secret:
        secretName: app-secret
 